site_name: EngineCPP
theme: 'windmill'
nav:
    - 'Architecture Overview': 'architecture_overview.md'
    - 'Ressource': 'ressource.md'
    - 'Scene': 'scene.md'
    - 'Render': 'render.md'
    - 'GPU': 'gpu.md'
extra_javascript:
    - ./js/custom.js
extra_css:
    - ./css/custom.css