site_name: Engine
theme: 'windmill'
nav:
    - 'Architecture Overview': 'architecture_overview.md'
    - 'Resource': 'resource.md'
    - 'Resources':
          - 'Render resource': 'render_resource.md'
    - 'AssetDatabase': 'asset_database.md'
    - 'Scene': 'scene.md'
    - 'Scene Middleware': 'scene_middleware.md'
    - 'Scene Middlewares':
          - 'Render middleware': 'render_middleware.md'
    - 'Render': 'render.md'
    - 'GPU': 'gpu.md'
extra_javascript:
    - ./js/custom.js
extra_css:
    - ./css/custom.css