set(PARAM_STATIC true)
set(PARAM_SHARED false)

function(target_link_name project type p_path p_name p_debug p_static)
    if (WIN32)
        if (p_static)
            set(lib_extension lib)
        else ()
            set(lib_extension dll)
        endif ()

        if (p_debug)
            target_link_libraries(${project} ${type} "${p_path}/${p_name}d.${lib_extension}")
        else ()
            target_link_libraries(${project} ${type} "${p_path}/${p_name}.${lib_extension}")
        endif ()
    else ()
        if (p_static)
            set(lib_extension a)
        else ()
            set(lib_extension so)
        endif ()

        target_link_libraries(${project} ${type} "${p_path}/lib${p_name}.${lib_extension}")
    endif ()
endfunction()